backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "chapter"
    label: "Chapter Info"
    files:
      - file: "content/chapter.json"
        label: "Chapter Info"
        name: "chapter"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "City", name: "city", widget: "string" }
          - { label: "State", name: "state", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Welcome Message", name: "welcomeMessage", widget: "text" }
  - name: "events"
    label: "Events"
    file: "content/events.json"
    label_singular: "Event"
    widget: "list"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "board"
    label: "Board"
    files:
      - file: "content/board.json"
        label: "Board"
        name: "board"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
